const pizzas = [
  {
    id: 1,
    name: "Margherita",
    ingredients: ["Tomato", "Mozzarella", "Basil"],
    price: 5.0,
    photo: null,
    soldOut: false,
  },
  {
    id: 2,
    name: "Pepperoni",
    ingredients: ["Tomato", "Mozzarella", "Pepperoni"],
    price: 6.5,
    photo: null,
    soldOut: false,
  },
  {
    id: 3,
    name: "Quattro Stagioni",
    ingredients: [
      "Tomato",
      "Mozzarella",
      "Mushrooms",
      "Ham",
      "Artichokes",
      "Olives",
    ],
    price: 7.0,
    photo: null,
    soldOut: false,
  },
  {
    id: 4,
    name: "Capricciosa",
    ingredients: ["Tomato", "Mozzarella", "Mushrooms", "Artichokes", "Ham"],
    price: 6.5,
    photo: null,
    soldOut: false,
  },
  {
    id: 5,
    name: "Vegetariana",
    ingredients: [
      "Tomato",
      "Mozzarella",
      "Bell Peppers",
      "Zucchini",
      "Eggplant",
    ],
    price: 6.0,
    photo: null,
    soldOut: false,
  },
  {
    id: 6,
    name: "Hawaiian",
    ingredients: ["Tomato", "Mozzarella", "Ham", "Pineapple"],
    price: 6.5,
    photo: null,
    soldOut: true,
  },
  {
    id: 7,
    name: "Diavola",
    ingredients: ["Tomato", "Mozzarella", "Spicy Salami"],
    price: 6.0,
    photo: null,
    soldOut: false,
  },
  {
    id: 8,
    name: "Quattro Formaggi",
    ingredients: ["Tomato", "Mozzarella", "Parmesan", "Gorgonzola", "Fontina"],
    price: 7.5,
    photo: null,
    soldOut: false,
  },
  {
    id: 9,
    name: "Frutti di Mare",
    ingredients: ["Tomato", "Mozzarella", "Mixed Seafood"],
    price: 8.0,
    photo: null,
    soldOut: true,
  },
  {
    id: 10,
    name: "Prosciutto e Funghi",
    ingredients: ["Tomato", "Mozzarella", "Ham", "Mushrooms"],
    price: 6.5,
    photo: null,
    soldOut: false,
  },
];

export default pizzas;
